"""feat(models): add last_applied_month to recurring_payments

Revision ID: 194f4e65b6f9
Revises: f40c121b9056
Create Date: 2026-04-17 22:12:42.228539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194f4e65b6f9'
down_revision: Union[str, Sequence[str], None] = 'f40c121b9056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_payments', sa.Column('last_applied_month', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_payments', 'last_applied_month')
    # ### end Alembic commands ###
