"""feat(models): add paycheck_schedules and paychecks tables

Revision ID: ba01be045d2c
Revises: b7f3c9a1d2e4
Create Date: 2026-07-16 07:54:15.792635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba01be045d2c'
down_revision: Union[str, Sequence[str], None] = 'b7f3c9a1d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paycheck_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'SEMI_MONTHLY', 'MONTHLY', name='paycheckfrequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paychecks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['paycheck_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paychecks_schedule_id'), 'paychecks', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paychecks_schedule_id'), table_name='paychecks')
    op.drop_table('paychecks')
    op.drop_table('paycheck_schedules')
    # ### end Alembic commands ###
