"""feat(models): link transactions to paychecks

Revision ID: e4282cbdc88e
Revises: ba01be045d2c
Create Date: 2026-07-16 10:24:54.125618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4282cbdc88e'
down_revision: Union[str, Sequence[str], None] = 'ba01be045d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paycheck_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'paychecks', ['paycheck_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'paycheck_id')
    # ### end Alembic commands ###
