"""feat(models): add is_estimate/active to recurring_payments, active to paycheck_schedules

Revision ID: e6f096d5f610
Revises: e4282cbdc88e
Create Date: 2026-07-17 09:22:36.348869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f096d5f610'
down_revision: Union[str, Sequence[str], None] = 'e4282cbdc88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paycheck_schedules', sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('recurring_payments', sa.Column('is_estimate', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('recurring_payments', sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.alter_column('recurring_payments', 'day_of_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
    # Drop the server defaults now that existing rows are backfilled - new rows
    # rely on the SQLAlchemy-level default, matching the other boolean columns.
    op.alter_column('paycheck_schedules', 'active', server_default=None)
    op.alter_column('recurring_payments', 'is_estimate', server_default=None)
    op.alter_column('recurring_payments', 'active', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurring_payments', 'day_of_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recurring_payments', 'active')
    op.drop_column('recurring_payments', 'is_estimate')
    op.drop_column('paycheck_schedules', 'active')
    # ### end Alembic commands ###
