"""feat(models): add recurring payments table

Revision ID: f40c121b9056
Revises: 9484ddf91be9
Create Date: 2026-04-15 16:12:56.512322

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PGEnum
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40c121b9056'
down_revision: Union[str, Sequence[str], None] = '9484ddf91be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('category', PGEnum(name='category', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('recurring_payment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'recurring_payments', ['recurring_payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'recurring_payment_id')
    op.drop_table('recurring_payments')
    # ### end Alembic commands ###
